# Generated by Django 5.1.1 on 2024-09-16 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('damage', models.IntegerField()),
                ('cost', models.IntegerField()),
                ('size', models.IntegerField()),
                ('type', models.CharField(choices=[('consumable', 'Consumable'), ('tool', 'Tool'), ('weapon', 'Weapon'), ('ammo', 'Ammo')], max_length=10)),
                ('ammo_type', models.CharField(choices=[('compact', 'Compact'), ('medium', 'Medium'), ('long', 'Long'), ('special', 'Special'), ('shotgun', 'Shotgun')], max_length=7)),
                ('effective_range', models.IntegerField()),
                ('rate_of_fire', models.IntegerField()),
                ('cycle_time', models.IntegerField()),
                ('spread', models.IntegerField()),
                ('sway', models.IntegerField()),
                ('vertical_recoil', models.IntegerField()),
                ('muzzle_velocity', models.IntegerField()),
                ('light_melee_damage', models.IntegerField()),
                ('heavy_melee_damage', models.IntegerField()),
                ('light_melee_stamina', models.IntegerField()),
                ('heavy_melee_stamina', models.IntegerField()),
                ('light_melee_damage_type', models.CharField(choices=[('rending', 'Rending'), ('blunt', 'Blunt'), ('piercing', 'Piercing')], max_length=8)),
                ('heavy_melee_damage_type', models.CharField(choices=[('rending', 'Rending'), ('blunt', 'Blunt'), ('piercing', 'Piercing')], max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Loadout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('description', models.TextField()),
                ('weapon_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loadout_weapon_one', to='loadouts.gun')),
                ('weapon_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loadout_weapon_two', to='loadouts.gun')),
            ],
        ),
    ]
